### ISSUE TITLE
Draw Venn-Diagrams

### ISSUE THREAD

**Issue by m0ritz2k19** [siKruger/logic-set-trainer#3]
From a well formatted expression shall a Venn-Diagram be drawn.

Max size should be five sets.

**This task contains the DRAWINGS only!**

**Comment by siKruger** [comment]
+ explicit elements from set

**Comment by siKruger** [comment]
Vorerst auf halt, weil Anycharts noch nicht da ist.

**Comment by siKruger** [comment]
https://github.com/siKruger/logic-set-trainer/pull/52
